INSERT INTO MPA (ID, NAME) VALUES (1, 'G');
INSERT INTO MPA (ID, NAME) VALUES (3, 'PG-13');
INSERT INTO MPA (ID, NAME) VALUES (5, 'NC-17');
INSERT INTO MPA (ID, NAME) VALUES (2, 'unknown');
INSERT INTO MPA (ID, NAME) VALUES (4, 'unknown');

INSERT INTO GENRES (ID, NAME) VALUES (1, 'Комедия');
INSERT INTO GENRES (ID, NAME) VALUES (2, 'Драма');
INSERT INTO GENRES (ID, NAME) VALUES (3, 'Мультфильм');
INSERT INTO GENRES (ID, NAME) VALUES (4, 'Боевик');
INSERT INTO GENRES (ID, NAME) VALUES (5, 'Приключения');
INSERT INTO GENRES (ID, NAME) VALUES (6, 'Фентези');
